# Generated by Django 2.2.9 on 2019-12-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
