# Generated by Django 2.2.9 on 2019-12-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191225_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='body',
            new_name='description',
        ),
    ]
